version: '3.8'

services:
  sls0:
    image: postgres:15.1
    container_name: sls0
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432